# logger_name
# logger_level
# logger_file
logger:
  name: python25
  level: WARNING
  file: python25.txt

excel:
  file: cases.xlxs
  sheet: login

database:
  host: 120.78.128.25
  port: 3306
  user: future
  password: 123456
  charset: utf8
  database: futureloan
  cursorclass: DictCursor

user:
  mobile_phone: '13712341234'
  pwd: '12345678'